sudo: required
dist: trusty
language: cpp

matrix:
    include:
#       -   os: linux
#           compiler: clang
#
#           before_install:
#               - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#               - sudo apt-add-repository "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main"
#               - sudo apt-get update -q
#               - sudo apt-get install csh -y
#               - sudo apt-get install clang++-3.6 -y
#               - sudo apt-get install libboost-date-time-dev -y
#               - sudo apt-get install libboost-random-dev -y
#               - sudo apt-get install libblas-dev -y
#
#           env:
#               - MY_CXX=clang++-3.6
#               - LD_LIBRARY_PATH=/usr/local/lib

        -   os: linux
            compiler: gcc

            before_install:
                - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
                - sudo apt-get update -q
                - sudo apt-get install csh -y
                - sudo apt-get install g++-4.9 -y
                - sudo apt-get install libboost-date-time-dev -y
                - sudo apt-get install libboost-random-dev -y
                - sudo apt-get install libblas-dev -y

            env:
                - MY_CXX=g++-4.9
                - LD_LIBRARY_PATH=/usr/local/lib

install:
    - export CXX=$MY_CXX

script:
    - travis_scripts/script_linux.sh
