sudo: required
dist: trusty

language: cpp

matrix:
    include:
        -   
            os: linux
            compiler: clang
            addons:
                apt:
                    sources:
                        - llvm-toolchain-precise-3.6
                        - ubuntu-toolchain-r-test
                        - boost-latest
                    packages: 
                        - csh
                        - clang-3.6
                        - libc++-dev
                        - libboost-date-time1.55-dev
                        - libboost-random1.55-dev
                        - libblas-dev
                        - openssl
            env:
                - INSTALL_CXX=clang++-3.6
                - LD_LIBRARY_PATH=$HOME/lib
        -   
            os: linux
            compiler: gcc
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                        - boost-latest
                    packages: 
                        - csh
                        - g++-4.9
                        - libboost-date-time1.55-dev
                        - libboost-random1.55-dev
                        - libblas-dev
                        - openssl
            env:
                - INSTALL_CXX=g++-4.9
                - LD_LIBRARY_PATH=$HOME/lib

before_install:
    - mkdir $HOME/include
    - mkdir $HOME/lib

before_script:
    - if [ -n "$INSTALL_CXX" ]; then CXX=$INSTALL_CXX; fi

script:
    - travis_scripts/script_linux.sh
