# Sample SmartGridToolbox configuration file.
# File format is YAML.

--- # Marks the start of each configuration document.

global:
   configuration_name:        config_1
   start_date_time:           2013-01-23 13:13:00
   end_date_time:             2013-01-23 13:13:00

prototypes: # These define object types, for convenience.
   line:
      name:                   line_type_1 
      admittance:             [12+3i,   1+1i,    1+2i,    0,
                               0,       1+1i,    1+2i,    3+7i,
                               0,       1+1i,    1+2i,    3+7i,
                               0,       1+1i,    1+2i,    3+7i]


objects: # And these are the actual objects.
      house:
         name:                house_1
         area_sqm:            25.0
         heating_type:        hvac

      house:
         name:                house_2
         area_sqm:            28.0
         heating_type:        hvac

      bus:
         name:                bus_1
         bus_type:            PV # Generator bus
         constant_real_power: 3

      bus:
         name:                bus_2
         bus_type:            PQ 
         phases:              ABCN

      line:
         name:                line_1_2
         bus_1:               bus_1
         bus_2:               bus_2
         prototype:           line_type_1

--- # Marks the end of each configuration document.
